version = 0.1

[default.deploy.parameters]
stack_name = "aws-url-shortner-phase1"
resolve_s3 = true
s3_prefix = "aws-url-shortner-phase1"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
